# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  javadoc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download Peersim
      run: |
        wget http://downloads.sourceforge.net/project/peersim/peersim-1.0.5.zip
        unzip peersim-1.0.5.zip
        cp peersim-1.0.5/*.jar lib
    - name: Restore Maven cache
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build Javadoc
      run: mvn javadoc:javadoc -Dmpi.path=$PWD/lib -Dpeersim.path=$PWD/lib
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      if: ${{ github.event_name == 'push' }}
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: target/site/apidocs # The folder the action should deploy.
